//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzonTech.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Code_Application { get; set; }
        public string Name { get; set; }
        public string Name_Computer { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<System.DateTime> StatusUpdatedOn { get; set; }
        public Nullable<int> DepartamentId { get; set; }
        public Nullable<int> RequestCategoryId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual CategoryRequest CategoryRequest { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Users Users { get; set; }
    }
}
